import globals from "globals";
import js from "@eslint/js";
import { defineConfig } from "eslint/config";

export default defineConfig([
  {
    ignores: [
      "**/*.ejs",
      "data/**",
      "node_modules/**",
      "public/**",
      "uploads/**",
    ],
  },
  js.configs.recommended,
  {
    files: ["**/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      globals: {
        ...globals.browser,
        ...globals.node,
      },
      sourceType: "module",
    },
    rules: {
      "array-bracket-spacing": ["error", "never"],
      "arrow-body-style": ["error", "as-needed"],
      "arrow-spacing": ["error", { before: true, after: true }],
      "comma-dangle": ["error", "always-multiline"],
      curly: ["error", "all"],
      "eol-last": ["error", "always"],
      eqeqeq: ["error", "always"],
      indent: ["error", 2],
      "no-console": "off",
      "no-constant-condition": "error",
      "no-debugger": "error",
      "no-dupe-args": "error",
      "no-dupe-keys": "error",
      "no-eval": "error",
      "no-func-assign": "error",
      "no-implied-eval": "error",
      "no-import-assign": "error",
      "no-path-concat": "error",
      "no-process-exit": "off",
      "no-return-await": "error",
      "no-shadow": "error",
      "no-sync": "error",
      "no-throw-literal": "error",
      "no-trailing-spaces": "error",
      "no-undef": "error",
      "no-unreachable": "error",
      "no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
      "no-use-before-define": ["error", { functions: true, classes: true }],
      "no-useless-catch": "error",
      "no-useless-concat": "error",
      "no-useless-return": "error",
      "no-var": "error",
      "object-curly-spacing": ["error", "always"],
      "object-shorthand": ["error", "always"],
      "prefer-arrow-callback": "error",
      "prefer-const": "error",
      "prefer-template": "error",
      quotes: ["error", "double", { avoidEscape: true }],
      semi: ["error", "always"],
      "space-before-blocks": ["error", "always"],
    },
  },
]);
